version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_assignees:
      - "kyokutyo"
    allowed_updates:
      - match:
          update_type: "all"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
    version_requirement_updates: "off"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
